# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Trang chủ
    url: /
    weight: 10
  - name: Hướng nghiên cứu
    url: /#research
    weight: 20
  - name: Thành viên
    url: /#team
    weight: 30
  - name: Công bố khoa học
    url: /#papers
    weight: 40
  - name: Tin tức
    url: /#news
    weight: 50
  - name: Liên hệ
    url: /#contact
    weight: 60
